title: Alex
author: Alex Beattie
email: artisanb@me.com
description: > # this means to ignore newlines until "baseurl:"
  Just testing a site

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
